import os
import tempfile
import unicodedata
import uuid
from datetime import datetime, timezone

from fpdf import FPDF
from fpdf.enums import XPos, YPos


def _pdf_safe(text: str) -> str:
    """
    Normalize text for PDF core fonts (Latin-1).
    Characters outside the Latin-1 range are replaced with '?'.
    """
    if text is None:
        return "N/A"
    normalized = unicodedata.normalize("NFKD", str(text))
    return normalized.encode("latin-1", "replace").decode("latin-1")


class ReportService:
    """
    Service for generating wind turbine operation PDF reports using fpdf2.
    Saves real PDF files to the reports directory.
    """

    def generate(self, state: dict) -> str:
        correlation_id = state.get("correlation_id", "default_corr")

        # Cross-platform temporary folder support
        reports_dir = "/tmp/reports"
        if os.name == 'nt':
            reports_dir = os.path.join(tempfile.gettempdir(), "reports")
        os.makedirs(reports_dir, exist_ok=True)

        pdf_path = os.path.join(reports_dir, f"{correlation_id}.pdf")

        pdf = FPDF()
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()

        # Title
        pdf.set_font("helvetica", "B", 16)
        pdf.cell(
            0,
            10,
            "WindOps Copilot - Incident Report",
            new_x=XPos.LMARGIN,
            new_y=YPos.NEXT,
            align="C",
        )
        pdf.ln(6)

        pdf.set_font("helvetica", "", 12)

        fields = [
            ("Correlation ID", correlation_id),
            ("Turbine ID", state.get("turbine_id", "unknown")),
            ("Severity", state.get("severity", "low")),
            ("Root Cause", state.get("root_cause", "N/A")),
            ("Recommended Action", state.get("recommended_action", "N/A")),
            (
                "Timestamp",
                datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC"),
            ),
        ]

        for label, value in fields:
            pdf.set_font("helvetica", "B", 12)
            pdf.cell(55, 8, f"{_pdf_safe(label)}:", new_x=XPos.RIGHT, new_y=YPos.TOP)
            pdf.set_font("helvetica", "", 12)

            if label in ("Root Cause", "Recommended Action"):
                pdf.multi_cell(0, 8, _pdf_safe(value))
                pdf.ln(2)
            else:
                pdf.cell(
                    0,
                    8,
                    _pdf_safe(value),
                    new_x=XPos.LMARGIN,
                    new_y=YPos.NEXT,
                )

        # Footer
        pdf.set_y(-30)
        pdf.set_font("helvetica", "I", 10)
        pdf.set_text_color(128, 128, 128)
        pdf.cell(
            0,
            10,
            "WindOps Copilot | Generated by ReportService",
            align="C",
        )

        pdf.output(pdf_path)

        print(f"[ReportService] Generated report at: {pdf_path}")
        return pdf_path


class GmailService:
    """
    Asynchronous service for sending alert emails with attachments.
    Maintains an in-memory log of dispatched emails.
    """

    email_log: list[dict] = []

    async def send_alert(
        self,
        subject: str,
        body: str,
        attachment: str = None,
        recipient: str = None,
        turbine_id: str = None,
        severity: str = None,
        status: str = "sent",
        incident_id: str = None,
    ) -> bool:
        print("=== [GmailService] Dispatching Email Alert ===")
        print(f"Subject: {subject}")
        print(f"Attachment: {attachment}")
        print(f"Body (Truncated Preview):\n{body[:350]}...")
        print("==============================================")

        self.email_log.append(
            {
                "email_id": str(uuid.uuid4()),
                "sent_at": datetime.utcnow().isoformat(),
                "recipient": recipient or "ops@windops.local",
                "subject": subject,
                "body": body,
                "turbine_id": turbine_id or "unknown",
                "severity": severity or "medium",
                "status": status,
                "incident_id": incident_id,
            }
        )

        return True


# Singleton instances for easy import
report_service = ReportService()
gmail_service = GmailService()
